require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'ReactNativeTemplateWalletConnect' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ReactNativeTemplateWalletConnectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # https://github.com/tradle/react-native-udp/issues/113#issuecomment-692904125
      if target.name == 'CocoaAsyncSocket'
        source_files = target.source_build_phase.files
        dummy = source_files.find do |file|
          file.file_ref.name == 'GCDAsyncUdpSocket.m'
        end

        if dummy != nil
          source_files.delete dummy
          puts "Deleting source file #{dummy.inspect} from target #{target.inspect}."
        end
      end
    end

    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
